### ISSUE TITLE
Hackaton project BIDS

### ISSUE THREAD

**Issue by pvdemael** [OpenMRBenelux/openmrb2020-hackathon#11]
Hi,

I issued a new Hackaton project but forgot to use the Hackaton template, sorry for that...
Is it possible to change this and add labels
matlab | python | no code

Sorry for the inconvenience

**Comment by Remi-Gau** [comment]
No worries. You described things quite well and your project has pretty low requirements so this should be fine.
Are you OK with me adding the matlab and python labels even though there are not "necessary" to join or do you think that this could "scare" people away?

**Comment by pvdemael** [comment]
I am perfectly fine with that, thank you very much!!!
